server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: moon1208
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
          initial-size: 5
          max-idle: 5
          max-total: 20
          min-idle: 3
          validation-query: select 1
          test-on-borrow: true
          test-while-idle: true
          test-on-return: false
          max-wait-millis: 10000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html

my-name: demo
